name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set up Nix cache
        uses: cachix/cachix-action@v14
        with:
          name: smaug123
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build
        run: |
          readarray -d '' crates < <(find . -mindepth 2 -maxdepth 2 -type f -name Cargo.toml -print0)
          for crate in "${crates[@]}"; do
            nix build ".#$(basename "$(dirname "$crate")")"
          done

      - name: Clippy
        run: |
          readarray -d '' crates < <(find . -mindepth 2 -maxdepth 2 -type f -name Cargo.toml -print0)
          for crate in "${crates[@]}"; do
            nix build ".#clippy_$(basename "$(dirname "$crate")")"
          done

      - name: Test
        run: |
          readarray -d '' crates < <(find . -mindepth 2 -maxdepth 2 -type f -name Cargo.toml -print0)
          for crate in "${crates[@]}"; do
            name=".#test_$(basename "$(dirname "$crate")")"
            exit_code=$(nix build "$name")
            if [ "$exit_code" -ne 0 ]; then
              nix log "$name"
              exit "$exit_code"
            fi
          done

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run Alejandra
        run: nix develop --command alejandra .

      - name: Run cargo fmt
        run: nix develop --command cargo fmt --check

  all-required-checks-complete:
    needs: [format, tests]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: G-Research/common-actions/check-required-lite@2b7dc49cb14f3344fbe6019c14a31165e258c059
        with:
          needs-context: ${{ toJSON(needs) }}

